heat_template_version: 2015-04-30

parameters:
  top-level:
    type: string

resources:
  nested-group:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: jdob::Nested1
        properties:
          nested-1-param: {get_param: top-level}
