heat_template_version: 2015-04-30

description: child template

parameters:

  attr-value:
    description: passed in as an attribute of another parent resource
    type: string

  param-value:
    description: passed in from parameter value in parent template
    type: string

  literal-value:
    description: literal hardcoded in child resource definition
    type: string

  unspecified-value:
    description: unspecified by parent
    type: string
    default: default-in-child

resources:

  dummy:
    type: OS::Heat::None
