heat_template_version: 2015-04-30

description: parent template

parameters:

  input-1:
    type: string

resources:

  rand:
    type: OS::Heat::RandomString
    properties:
      length: 4

  child:
    type: jdob::Child
    properties:
      attr-value: { get_attr: [rand, value] }
      param-value: { get_param: input-1 }
      literal-value: hard-coded
