heat_template_version: 2014-10-16

parameters:

  image:
    type: string
    default: fedora-sd

  key_name:
    type: string
    default: heat-key

  flavor:
    type: string
    default: m1.small

resources:

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: SOFTWARE_CONFIG

  create_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: filepath
      outputs:
      - name: result
      config: |
        #!/bin/sh -x
        echo "Executing create config"
        echo "Create Software Deployment" > /tmp/$filepath
        echo "Created /tmp/$filepath on server $deploy_server_id during $deploy_action" > $heat_outputs_path.result

  create_deployment_1:
    type: OS::Heat::SoftwareDeployment
    properties:
      server: { get_resource: server }
      config: { get_resource: create_config }
      input_values:
        filepath: create-deployment-file-1

  create_deployment_2:
    type: OS::Heat::SoftwareDeployment
    properties:
      server: { get_resource: server }
      config: { get_resource: create_config }
      input_values:
        filepath: create-deployment-file-2

  delete_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/sh -x
        echo "Executing delete config"
        echo "This should only be present on delete" > /tmp/delete-deployment

  delete_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      server: { get_resource: server }
      config: { get_resource: delete_config }
      actions: ['DELETE']
