heat_template_version: 2015-04-30

parameters:

  p1:
    type: string
    default: template-default-p1

  p2:
    type: string
    default: template-default-p2

  p3:
    type: string
    default: template-default-p3

  p4:
    type: string
    default: template-default-p4

  p5:
    type: string
    default: template-default-p5

outputs:

  p1-value:
    value: { get_param: p1 }
    description: not overridden in an environment file

  p2-value:
    value: { get_param: p2 }
    description: set in parameters in first env, parameter_defaults in second

  p3-value:
    value: { get_param: p3 }
    description: set in parameter_defaults in first env, parameters in second

  p4-value:
    value: { get_param: p4 }
    description: set in parameters in both first and second

  p5-value:
    value: { get_param: p5 }
    description: set in parameter_defaults in both first and second
