heat_template_version: 2016-04-08

parameters:
  chain-types:
    type: comma_delimited_list
    default: ['OS::Heat::RandomString', 'OS::Heat::RandomString']

resources:
  my-chain:
    type: OS::Heat::ResourceChain
    properties:
      resources: { get_param: chain-types }
