heat_template_version: 2015-04-30

parameters:

  key_name:
    type: string
    description: keypair to enable SSH access to the instance
    default: demo-key

  image_id:
    type: string
    description: ID of the image to use for the instance
    default: cirros-0.3.4-x86_64-uec
    constraints:
      - allowed_values: ['cirros-0.3.4-x86_64-uec', 'fedora-22.x86_64']

  flavor:
    type: string
    description: Nova flavor of the instance to create
    default: m1.tiny
    constraints:
      - allowed_values: ['m1.tiny', 'm1.small', 'm1.medium']

  demo_text:
    type: string
    description: demo text to stuff into sample file


resources:

  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }

      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            echo "DEMO_TEXT" > /tmp/demo-file
          params:
            DEMO_TEXT: { get_param: demo_text }


outputs:
  networks:
    description: assigned IP address of the instance
    value: { get_attr: [my_instance, networks] }
