heat_template_version: 2016-04-08

parameters:

  image:
    type: string
    default: cirros-0.3.4-x86_64-uec

  key_name:
    type: string
    default: heat-key

  flavor:
    type: string
    default: m1.small

  min_node_count:
    type: number
    default: 1

  max_node_count:
    type: number
    default: 3

resources:

  servers:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: { get_param: min_node_count }
      max_size: { get_param: max_node_count }
      resource:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }

outputs:
  resource_refs:
    value: { get_attr: [servers, refs] }
  resource_map:
    value: { get_attr: [servers, refs_map] }
