heat_template_version: 2013-05-23

description: deploys a single server

parameters:

  image:
    type: string
    description: image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
  key_name:
    type: string
    description: existing key pair to use for the server
    default: heat-key
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: flavor for the server to be created
    default: m1.tiny
    constraints:
      - custom_constraint: nova.flavor

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
